### ISSUE TITLE
Current version fails tests with 2019.03.1

### ISSUE THREAD

**Issue by JJ** [finanalyst/pod-cached#13] opened 2019-07-17 17:07 UTC
This was working a short time ago, all of a sudden it's failed.

```
===> Testing: Pod::To::Cached:ver<0.3.0>
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of uninitialized value of type Status in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 369
# Failed test 'One current, one tainted'
# at t/020-source.t line 137
# expected: ${:a-pod-file("Current"), :a-second-pod-file("Valid")}
#      got: ${:a-pod-file(""), :a-second-pod-file("Valid")}
# Failed test 'List with list of statuses'
# at t/020-source.t line 139
# expected: $("a-pod-file", "a-second-pod-file")
#      got: $("a-second-pod-file",)
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of uninitialized value of type Status in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 369
# Failed test 'One current, one tainted'
# at t/020-source.t line 156
# expected: ${:a-pod-file("Valid"), :a-second-pod-file("Current")}
#      got: ${:a-pod-file("Valid"), :a-second-pod-file("")}
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
# Looks like you failed 3 tests of 36
# test pod extraction
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Use of Nil in string context
  in block  at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 170
Attempt to obtain non-existent POD for <a-pod-file>. Is the source new and failed to compile? Has the cache been updated?
  in method pod at /home/jmerelo/progs/forks/perl6/pod-cached/lib/Pod/To/Cached.pm6 (Pod::To::Cached) line 344
  in block <unit> at t/040-pod-extraction.t line 18

# Heavy duty test optional
===> Testing [FAIL]: Pod::To::Cached:ver<0.3.0>
Aborting due to test failure: Pod::To::Cached:ver<0.3.0> (use --force-test to override)
```

**Comment by finanalyst** [comment] 2019-07-17 17:53
This is strange. I haven't changed the module.

**Comment by finanalyst** [comment] 2019-07-17 19:55
Interesting.
1) I merged the changes made by JJ 16 days ago. I didn't verify on my computer.
2) I just now 'pulled' the current github code to my computer, and ran `prove -ve perl6`
3) I got the same errors as listed for Windows, but I am running Ubuntu!
perl6 -v => `Rakudo version 2018.12 built on MoarVM version 2018.12`

According to noisegul in issue #15 reports that he has no problems with Rakudo Star version 2019.3

I am upgrading perl6 to 2019.3 and will test again

Update: upgraded to Rakudo Star 2019.3, still getting errors.

**Comment by finanalyst** [comment] 2019-07-18 11:39
The problem is caused by an update in JSON::Fast from version 0.9.12 to 0.9.18
I had a setup with JSON::Fast 0.9.12, and my original module worked.
When I updated to JSON::Fast 0.9.18, the original module failed, but the change by JJ allowed the tests to pass in Linux OS.

**Comment by finanalyst** [comment] 2019-07-18 11:57
The problem in Linux is related to the update in JSON::Fast.
I will change the META file to require a version greater than 0.9.18

**Closed as completed by finanalyst** 2019-07-18 11:57 UTC
