### ISSUE TITLE
The constructor wrongly assumed the existence of a cache if the directory exists

### ISSUE THREAD

**Issue by JJ** [finanalyst/pod-cached#17] opened 2019-08-03 09:26 UTC
So there's no way to tell it to create a cache in an already existing directory.

**Comment by finanalyst** [comment] 2019-08-10 09:03
I suppose it depends on what is meant by a cache.
My idea is that the specially named directory is the cache.
If the cache directory does not contain the necessary files, which include the yaml index, then the cache is corrupt.
So a correct cache is 1) named directory 2) specific files.
Perhaps we should define this.

**Comment by finanalyst** [comment] 2019-08-31 16:51
I would like to close this issue.
A cache is by design 1) directory source + 2) yaml index file. Existence of a directory without a yaml index file is therefore a corrupt cache, by design.

**Closed as completed** 2019-09-04 05:21 UTC
